FROM golang:1.18-alpine3.15

WORKDIR /app/go/base

RUN apk add --no-cache --update-cache \
    protoc

RUN go install github.com/cosmtrek/air@latest && \
    go install github.com/golang/protobuf/protoc-gen-go@latest && \
    go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

COPY . .

RUN go mod tidy
